### ISSUE TITLE
failing dependents.info action

### ISSUE THREAD

**Issue by gouravkhunger** [joshnuss/svelte-local-storage-store#309]
Hi @joshnuss just realised you're trying to use [dependents.info](https://dependents.info) on this repo, thanks for that!

I see the action is failing, which im not sure why. everything seems to be fine simulating a local run:

<img width="662" alt="Image" src="https://github.com/user-attachments/assets/9dcc73fb-0f0a-491d-b74b-32df91b84fe3" />

 To debug, it would be better if you set the `upload-artifacts` to be `true` so that I can debug?

```yaml
  - uses: gouravkhunger/dependents.info@main
    with:
      upload-artifacts: true
```

You dont have to do it on main branch else it might get polluted with commits. just use the Run workflow option on [this page](https://github.com/joshnuss/svelte-persisted-store/actions/workflows/dependents.yml) for the new branch.
